document_hash = "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
salt = "0x0abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789"
commitment = "0x2de81b14360c7f454fbb293eb1fd7529e7437a3e9b9a2e4810bebb3fe2ff283c"
current_timestamp = "1739577600"
