[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
fs_permissions = [{ access = "read", path = "../circuits" }]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
arbitrum_sepolia = "${RPC_URL}"
